apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-multi-com-tls # yourdomain-com-tls
spec:
  secretName: k8s-multi-com # yourdomain-com. Auto created secret by Cert Manager
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: k8s-multi.com # yourdomain.com
  dnsNames:
    - k8s-multi.com # yourdomain.com
    - www.k8s-multi.com # www.yourdomain.com